"""Add subscription fields to User model

Revision ID: 340227521e6b
Revises: a612775f5a92
Create Date: 2025-08-05 12:43:48.569229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340227521e6b'
down_revision = 'a612775f5a92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###