"""Add supabase_user_id to User model

Revision ID: a612775f5a92
Revises: 7ecc7f3a59fd
Create Date: 2025-08-05 11:58:47.051822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a612775f5a92'
down_revision = '7ecc7f3a59fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###